name: Testing of the action

on:
  push:
    branch:
      - test

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run action
        uses: ./
        with:
          repo_url: ${{ secrets.REPO_URL }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
      - name: repository content
        run: |
          ls
