name: Checkout an Azure Repo
description: Action that allows to download and/or update an Azure Repo with submodules. Works with both Azure credentials and Azure Token

inputs:
  repo_url:
    description: 'url of the Azure Repo. For example: azure.com/owner/repo'
    required: true
  repo_name:
    description: name of the cloned folder
    required: true
  submodules:
    description: boolean value which defines if the repository has submodules to update
    required: false
    default: false
  token:
    description: valid token from an Azure account
    required: true
  username: 
    required: true
  password:
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set git config
      shell: bash
      run: |
        git config --global user.name "${{ inputs.username }}"
        git config --global user.email "azure@azure.com"

    - name: Clone repository
      shell: bash
      run: |
        git clone https://${{ inputs.username }}:${{ inputs.token }}@${{ inputs.repo_url }}

  