name: Checkout an Azure Repo
description: Action that allows to download and/or update an Azure Repo with submodules

inputs:
  repo_url:
    description: full url of the Azure Repo, in HTTPS
    required: true
  submodules:
    description: boolean value which defines if the repository has submodules to update
    required: false
    default: false
  username: 
    required: true
  password:
    required: true

runs:
  using: 'composite'
  steps: 
    - name: Set credentials
      shell: bash
      run: |
        echo 'hola'
    - name: Clone repository
      shell: bash
      run: |
        git clone ${{ inputs.repo_url }}  

  