name: Testing the action

on:
  push:
    branches:
      - main

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run action 
        uses: ./
        with:
          repo_url: ${{ secrets.REPO_URL }}
          username: ${{ secrets.AZURE_USERNAME }}
          token: ${{ secrets.AZURE_TOKEN }}
      - name: repository content
        run: ls