name: Testing of the action

on:
  push:
    branch:
      - main

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run action 
        uses: ./
        with:
          repo_url: ${{ secrets.REPO_URL }}
          username: ${{ secrets.AZURE_USERNAME }}
          token: ${{ secrets.AZURE_TOKEN }}
          repo_name: NU0051001_Security_Services
      - name: repository content
        run: |
          ls